### ISSUE TITLE
Review and verify not working after popup appears

### ISSUE THREAD

**Issue by vipinross001** [neonexchange/nex-extension-alpha#10]
After filling the kyc details I clicked "review and verify" and popup appeared but when I clicked on. "These are correct" nothing is happening and I am stuck their only . Please check

**Comment by kvanquang** [comment]
Got the same problem, I even cleared cache and reinstalled Nex extension.

**Comment by gnewman89** [comment]
I am having the exact same problem. Everything is correct and after I click on "Confirm and continue" nothing happens. I also tried reinstalling Nex extension and using a different computer

**Comment by happybkkben** [comment]
I have the exact same problem. Please help with it. I stopped all blockers/anti virus, restarted both chrome and computer (Mac), emptied cache Etc. with no luck.

**Comment by wkostn** [comment]
I just successfully completed the registration after having the similar issue. Not sure if this will help you but after the popup you have to re-enter your password. If you then click first on the extension again the popup appears on another location, then registration was successfull for me.

**Comment by zgligoric** [comment]
Thank You wkosten1982, it works for me!

**Comment by happybkkben** [comment]
Thank you Wkosten! Worked for me too. Gotta wonder how the heck you figured that one out! :o)

**Comment by vipinross001** [comment]
it is not working for me . please help

**Comment by bGENT33** [comment]
@zgligoric @happybkkben @wkosten1982 hi guys- desperately trying to enter my KYC but having the same problem that you seemed to have solved, from the instructions listed above I cant figure out how to solve the issue. mainly - where do I have to enter my password, and by extension do you mean the chrome NEX extension - as this just shows my wallet details when i click on it. thanks so much in advance! B

**Comment by localhuman** [comment]
please see #13

**Comment by bGENT33** [comment]
@localhuman, please explain the process in more detail!
