### ISSUE TITLE
Again and again coming on same page " Review and verify "

### ISSUE THREAD

**Issue by vipinross001** [neonexchange/nex-extension-alpha#16]
After I enter my details and proceed to review and verify, it just returns to the same page asking me to review and verify again. i registered for the lottery. Now it just returns to the screen and does nothing. Please look into this as KYC closes soon. I have also attached the screenshot too and i am facing this issue while doing login via my private keys or encrypted keys with passphrase . Please check and remove the bug Thank you

Replication steps:

Enter KYC details
Click 'Review and verify' button
Click 'These are correct' button
Enter private key and confirm 
Page returns to No. 2
![screenshot 21 _li](https://user-images.githubusercontent.com/38094567/38385109-a348e87a-392e-11e8-99e9-a944cedc15b2.jpg)

**Comment by vipinross001** [comment]
also tried with entering encrypted keys and passphrase but still after clicking on the last step decrypt and continue , the popup disappears and we are seeing the same page of review and verify .  Please resolve asap

**Comment by localhuman** [comment]
Please see #13
