### ISSUE TITLE
Review and Verify Bug - please fix

### ISSUE THREAD

**Issue by bGENT33** [neonexchange/nex-extension-alpha#17]
Hi there - 

much like other KYC applicants in the below issues, once I enter in my password to complete the stage 1 of the KYC the 'review and verify' section does not load further. I have tried now 5 times to click 'These are correct' and it keeps returning to the review and verify section with the pop up window disappearing. 

With the KYC closing on the 7th - please fix this bug. 

Thanks
B

![screen shot 2018-04-05 at 21 02 15](https://user-images.githubusercontent.com/38113897/38386349-ae35c128-3914-11e8-9f17-812b7822bc44.png)

**Comment by p1nkdust** [comment]
Same issue! any ideas on what to do. I've restarted chrome and still get the same issue over and over. Please help!

**Comment by localhuman** [comment]
Please see the solution in #13

**Comment by bGENT33** [comment]
@localhuman this solution is not clear - please explain.
