### ISSUE TITLE
username not stored locally

### ISSUE THREAD

**Issue by rayjay79** [neonexchange/nex-extension-alpha#41]
I successfully won the lottery but can contribute, I cannot access my nex alpha extension it constantly say's user name not stored locally.  I've had computer problems cant locate private my private key. I know the user and password is correct as i open frequently.  I have deleted chrome and aplha and re-installed but still nothing.
I sent NEX several emails days ago for assistance. 
Help would be greatly appreciated before ico deadline.

**Comment by kecastro** [comment]
@rayjay79 Did you find a possible solution?

**Comment by rayjay79** [comment]
No,

Sent from my iPhone

On 13 Dec 2018, at 7:32 am, Kevin Castro <notifications@github.com<mailto:notifications@github.com>> wrote:


@rayjay79<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frayjay79&data=02%7C01%7C%7Ca27028af603040cebf7f08d66070edd3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636802435503052681&sdata=uH2SrxN308v9eXF5zT%2F5T0nuZW4IeV7oSe0D3jCf8sk%3D&reserved=0> Did you find a possible solution?

**Comment by canesin** [comment]
I explain how this works here: https://www.youtube.com/watch?v=BTxOSj_xSKQ
