### ISSUE TITLE
Mr Phuong

### ISSUE THREAD

**Issue by ptphan** [neonexchange/nex-extension-alpha#42]
Can I transfer Ont tokens to nex-extension wallet ? 
Please help

**Comment by ptphan** [comment]
![img_4910](https://user-images.githubusercontent.com/36834696/45263819-63e5a300-b474-11e8-9ccc-858a3eecf9c3.JPG)

**Comment by ptphan** [comment]
after 3 days, my ont tokens still not in nex-extension wallet yet.
can someone please help me.

**Comment by canesin** [comment]
ONT changed from a NEP5 to its own mainnet, you should use a Ontology wallet now.
