### ISSUE TITLE
Username not stored locally - possible solution similar to Metamask?

### ISSUE THREAD

**Issue by domenpepe** [neonexchange/nex-extension-alpha#43]
I was reckles and I have done the one thing you sholdnt do on the decentralized network and that is lost my private key as well as back up key. However I still have my username and password, but cannot use them because  I reinstalled the extension which now reports back that the username is not stored locally. Trying to solve my problem I stumbled upon this thread: https://github.com/MetaMask/metamask-extension/issues/2749

Is there maybe a similar solution with nex extension? If yes, which file would be the one that contains the appropriate user data?

PS: I managed to recover some of my previous extension data.

**Comment by kecastro** [comment]
@domenpepe Hi, were you able to find a solution?

**Comment by domenpepe** [comment]
@kecastro no unfortunately not. Do you have any ideas or info?

**Comment by kecastro** [comment]
@domenpepe Not really, I guess contacting one of the developers will help answer the question once and for all.

**Comment by canesin** [comment]
@domenpepe that is very unfortunate (lose both keys and re-install the extension) but maybe you can look for the log level file inside Chrome Local storage folders

On linux it is: `~/.config/google-chrome/Default/Local Extension Settings`
